### ISSUE TITLE
ERROR: BoundsError

### ISSUE THREAD

**Issue by GuillaumeDesforges** [chkwon/TrafficAssignment.jl#9]
I installed Sydney data from https://github.com/bstabler/TransportationNetworks
I modified load_ta_network by adding :

    elseif network_name == "Sydney"
        network_data_file = "Sydney_net.txt"
        trip_table_file = "Sydney_trips.txt"
        best_objective = 1.0

at line 65.

Then on Julia :

> ta_data = load_ta_network("Sydney")

Took a while but it seemed to work :
`TrafficAssignment.TA_Data("Sydney",3264,33113,3265,75379,[1,2,3,4,5,6,7,8,9,10  …  33108,33108,33109,33109,33110,33110,33111,33111,33112,33113],[6706,33087,30799,30800,6692,30791,30801,30789,30802,28781  …  7395,33109,33108,33111,21114,21116,33085,33109,6764,8902],[2880.0,2880.0,2880.0,2880.0,2880.0,2880.0,2880.0,2880.0,2880.0,2880.0  …  1800.0,1800.0,1800.0,1800.0,1773.0,1773.0,1800.0,1800.0,1844.0,1742.0],[0.904,0.027,0.257,0.123,0.068,0.103,0.068,0.033,0.029,0.066  …  1.687,1.377,1.377,2.442,0.457,0.119,2.902,2.442,0.664,0.194],[2.26,0.07,0.64,0.31,0.17,0.26,0.17,0.08,0.07,0.17  …  1.69,1.38,1.38,2.44,0.5,0.13,2.9,2.44,0.57,0.23],[0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25  …  0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25],[4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0  …  4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0],[24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0  …  60.0,60.0,60.0,60.0,55.0,55.0,60.0,60.0,70.0,50.0],[19.2,19.2,19.2,19.2,19.2,19.2,19.2,19.2,19.2,19.2  …  48.0,48.0,48.0,48.0,44.0,44.0,48.0,48.0,56.0,40.0],[2,2,2,2,2,2,2,2,2,2  …  1,1,1,1,1,1,1,1,1,1],849339.0,[0.0 0.0 … 0.0 0.03; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.03 0.0 … 0.0 0.0],Tuple{Int64,Int64}[(1,1),(1,2),(1,3),(1,4),(1,5),(1,6),(1,7),(1,8),(1,9),(1,10)  …  (3264,3255),(3264,3256),(3264,3257),(3264,3258),(3264,3259),(3264,3260),(3264,3261),(3264,3262),(3264,3263),(3264,3264)],0.0,0.0,1.0)`

Then I try to test :

> link_flow, link_travel_time, objective = ta_frank_wolfe(ta_data, log="on", max_iter_no=50000, tol=1e-1)

But I get an error :

`ERROR: BoundsError
 in getindex(::SparseMatrixCSC{Int64,Int64}, ::Int64, ::Int64) at .\sparse\sparsematrix.jl:2089
 in get_vector(::LightGraphs.DijkstraState{Float64}, ::Int64, ::Int64, ::SparseMatrixCSC{Int64,Int64}) at C:\Users\aceus\.julia\v0.5\TrafficAssignment\src\misc.jl:40
 in (::TrafficAssignment.#all_or_nothing_single#10)(::Array{Float64,1}) at C:\Users\aceus\.julia\v0.5\TrafficAssignment\src\frank_wolfe.jl:142
 in all_or_nothing at C:\Users\aceus\.julia\v0.5\TrafficAssignment\src\frank_wolfe.jl:186 [inlined]
 in #ta_frank_wolfe#1(::Symbol, ::Int64, ::Symbol, ::String, ::Float64, ::Function, ::TrafficAssignment.TA_Data) at C:\Users\aceus\.julia\v0.5\TrafficAssignment\src\frank_wolfe.jl:205
 in (::TrafficAssignment.#kw##ta_frank_wolfe)(::Array{Any,1}, ::TrafficAssignment.#ta_frank_wolfe, ::TrafficAssignment.TA_Data) at .\<missing>:0`

**Comment by chkwon** [comment]
I'll take a look. Could you tell me which version of Julia you are using?

**Comment by GuillaumeDesforges** [comment]
Version 0.5.0 (2016-09-19 18:14 UTC)
Official http://julialang.org/ release
x86_64-w64-mingw32

Thanks !

**Comment by chkwon** [comment]
For Julia v0.6 (currently rc1), you can update TrafficAssignment to version `v0.4.0` and you can now load Sydney data.

```
ta_data = load_ta_network("Sydney")
```

Although it takes forever to proceed one iteration because of the large size of the Sydney data, it did not produce any error at least for me. Let me know how it goes with you.
